# Assignment-3

This notebook contains the coding questions to test the proficiency in `Pandas` library in python.

### Date: 30th August, 2026

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the questions in the notebook and save it.
- Rename the file as `Assignment-03-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-03-Dipika_Chopra.ipynb`.
- Upload the solved notebook in your github repo under the folder **Assignment-3**.
- Upload the solved notebook in the google drive location: https://drive.google.com/drive/folders/1QVDdoiNNG1XRol0nFZIE7DHtQlHR0t6c?usp=drive_link 
<h3><span style="color:red"> Deadline: 20th September, 2026 </span></h3>

Use the `population_by_county.csv` file in the folder to complete the tasks.

**NOTE: TRY TO DO ALL THE TASKS IN ONE LINE OF PANDAS CODE.**

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/divyamalika/Library/Python/3.12/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/divyamalika/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 46.6 MB/s eta 0:00:00 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.5

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

#### 1. Import pandas and read in the `population_by_county.csv` file into a dataframe called `pop`.

In [19]:
# Write your code here

pop = pd.read_csv("./population_by_county.csv")

pop

                County           State  2010Census  2017PopEstimate
0     Abbeville County  South Carolina       25417            24722
1        Acadia Parish       Louisiana       61773            62590
2      Accomack County        Virginia       33164            32545
3           Ada County           Idaho      392365           456849
4         Adair County            Iowa        7682             7054
...                ...             ...         ...              ...
3137       Yuma County         Arizona      195751           207534
3138       Yuma County        Colorado       10043            10075
3139     Zapata County           Texas       14018            14322
3140     Zavala County           Texas       11677            11948
3141    Ziebach County    South Dakota        2801             2756

[3142 rows x 4 columns]

#### 2. Show the head of the dataframe, Also show top 8 rows of the dataframe using head

In [20]:
# Write your code here
pop.head()

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054

In [21]:
pop.head(8)

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
5      Adair County        Kentucky       18656            19485
6      Adair County        Missouri       25607            25377
7      Adair County        Oklahoma       22683            21909

#### 3. What are the column names?

In [26]:
pop.columns

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='str')

#### 4. How many States are represented in this data set?  
<em>Note: the data includes the `District of Columbia`</em>

In [30]:
pop['State'].nunique()

# pop['State'].value_counts()

51

#### 5. Get a list or array of all the states in the data set.

In [ ]:
pop['State'].values

<StringArray>
['South Carolina',      'Louisiana',       'Virginia',          'Idaho',
           'Iowa',       'Kentucky',       'Missouri',       'Oklahoma',
       'Colorado',          'Idaho',
 ...
 'South Carolina',       'Virginia',          'Texas',     'California',
         'Alaska',        'Arizona',       'Colorado',          'Texas',
          'Texas',   'South Dakota']
Length: 3142, dtype: str

In [33]:
pop_state_array = pop.to_numpy()

pop_state_array

array([['Abbeville County', 'South Carolina', 25417, 24722],
       ['Acadia Parish', 'Louisiana', 61773, 62590],
       ['Accomack County', 'Virginia', 33164, 32545],
       ...,
       ['Zapata County', 'Texas', 14018, 14322],
       ['Zavala County', 'Texas', 11677, 11948],
       ['Ziebach County', 'South Dakota', 2801, 2756]],
      shape=(3142, 4), dtype=object)

#### 6. What are the five most common County names in the U.S.?

In [35]:
pop['County'].value_counts().head(5)

County
Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: count, dtype: int64

#### 7. What are the top 5 most populated Counties according to the 2010 Census?

In [45]:
# Write your code here
pop.sort_values(by='2010Census', ascending=False)[['County','2010Census']].head(5)

                  County  2010Census
1713  Los Angeles County     9818605
628          Cook County     5194675
1209       Harris County     4092459
1784     Maricopa County     3817117
2501    San Diego County     3095313

In [49]:
pop.nlargest(5, '2010Census')[['County']]

                  County
1713  Los Angeles County
628          Cook County
1209       Harris County
1784     Maricopa County
2501    San Diego County

#### 8. What are the top 5 most populated States according to the 2010 Census?

In [46]:
pop.sort_values(by='2010Census', ascending=False)[['State','2010Census']].head(5)

           State  2010Census
1713  California     9818605
628     Illinois     5194675
1209       Texas     4092459
1784     Arizona     3817117
2501  California     3095313

#### 9. How many Counties have 2010 populations greater than 1 million?

In [55]:
pop.columns

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='str')

In [60]:
pop[pop['2010Census'] > 1_000_000]

                     County          State  2010Census  2017PopEstimate
25           Alameda County     California     1510271          1663190
45         Allegheny County   Pennsylvania     1223348          1223048
200            Bexar County          Texas     1714773          1958578
276            Bronx County       New York     1385108          1471160
283          Broward County        Florida     1748066          1935878
527            Clark County         Nevada     1951269          2204079
624     Contra Costa County     California     1049025          1147439
628             Cook County       Illinois     5194675          5211263
700         Cuyahoga County           Ohio     1280122          1248514
712           Dallas County          Texas     2368139          2618148
897          Fairfax County       Virginia     1081726          1148433
971         Franklin County           Ohio     1163414          1291981
1209          Harris County          Texas     4092459          4652980
1243        Hennepin County      Minnesota     1152425          1252024
1269    Hillsborough County        Florida     1229226          1408566
1503            King County     Washington     1931249          2188649
1509           Kings County       New York     2504700          2648771
1713     Los Angeles County     California     9818605         10163507
1784        Maricopa County        Arizona     3817117          4307033
1910      Miami-Dade County        Florida     2496435          2751796
1912       Middlesex County  Massachusetts     1503085          1602947
2042          Nassau County       New York     1339532          1369514
2063        New York County       New York     1585873          1664727
2105         Oakland County       Michigan     1202362          1250836
2139          Orange County     California     3010232          3190400
2140          Orange County        Florida     1145956          1348975
2186      Palm Beach County        Florida     1320134          1471150
2244    Philadelphia County   Pennsylvania     1526006          1580863
2366          Queens County       New York     2230722          2358582
2433       Riverside County     California     2189641          2423266
2484      Sacramento County     California     1418788          1530615
2495       Salt Lake County           Utah     1029655          1135649
2500  San Bernardino County     California     2035210          2157404
2501       San Diego County     California     3095313          3337685
2523     Santa Clara County     California     1781642          1938153
2715         Suffolk County       New York     1493350          1492953
2759         Tarrant County          Texas     1809034          2054475
2817          Travis County          Texas     1024266          1226698
2993           Wayne County       Michigan     1820584          1753616

#### 10. How many Counties don't have the word "County" in their name?

In [69]:
pop[~pop['County'].str.contains('County')]['County'].count()

np.int64(135)

In [70]:
pop[~pop['County'].str.contains('County')]

                          County      State  2010Census  2017PopEstimate
1                  Acadia Parish  Louisiana       61773            62590
32        Aleutians East Borough     Alaska        3141             3370
33    Aleutians West Census Area     Alaska        5561             5763
36               Alexandria city   Virginia      139966           160035
50                  Allen Parish  Louisiana       25764            25621
...                          ...        ...         ...              ...
3071             Winchester city   Virginia       26203            27932
3076                 Winn Parish  Louisiana       15313            14311
3104   Wrangell City and Borough     Alaska        2369             2521
3116    Yakutat City and Borough     Alaska         662              605
3136   Yukon-Koyukuk Census Area     Alaska        5588             5365

[135 rows x 4 columns]

#### 11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

In [72]:
pop.head()

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054

In [77]:
pop['PercentChange'] = (((pop['2017PopEstimate'] - pop['2010Census'])) / pop['2010Census'] * 100).round(2)

pop

,County,State,2010Census,2017PopEstimate,PercentChange
0,Abbeville County,South Carolina,25417,24722,-2.73
1,Acadia Parish,Louisiana,61773,62590,1.32
2,Accomack County,Virginia,33164,32545,-1.87
3,Ada County,Idaho,392365,456849,16.43
4,Adair County,Iowa,7682,7054,-8.17
...,...,...,...,...,...
3137,Yuma County,Arizona,195751,207534,6.02
3138,Yuma County,Colorado,10043,10075,0.32
3139,Zapata County,Texas,14018,14322,2.17
3140,Zavala County,Texas,11677,11948,2.32
3141,Ziebach County,South Dakota,2801,2756,-1.61

#### 12. What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?

**NOTE:** This will take several lines of code, as it requires a recalculation of Percent Change.

In [84]:
state_percent_change = pop.groupby('State')[['2010Census', '2017PopEstimate']].sum()

state_percent_change.head()

            2010Census  2017PopEstimate
State
Alabama        4779736          4874747
Alaska          710231           739795
Arizona        6392017          7016270
Arkansas       2915918          3004279
California    37253956         39536653

In [95]:
state_percent_change['PercentChange'] = (((state_percent_change['2017PopEstimate'] - state_percent_change['2010Census']) / state_percent_change['2010Census'] ) * 100).round(2)

state_percent_change.sort_values(by = 'PercentChange', ascending=False).head()

                      2010Census  2017PopEstimate  PercentChange
State
District of Columbia      601723           693972          15.33
Texas                   25145561         28304596          12.56
North Dakota              672591           755393          12.31
Utah                     2763885          3101833          12.23
Florida                 18801310         20984400          11.61

In [100]:
state_percent_change.sort_values(by = 'PercentChange', ascending=False).index[0]

'District of Columbia'

In [101]:
state_percent_change.sort_values(by = 'PercentChange', ascending=False).iloc[0]

2010Census         601723.00
2017PopEstimate    693972.00
PercentChange          15.33
Name: District of Columbia, dtype: float64